@startuml
participant "ServiceBusProcessorClient" as sdkClient <<Messaging Layer>> #lightskyblue
participant "ServiceBusMessageConsumer" as consumer <<Messaging Layer>> #lightskyblue
participant "MessageProcessor" as serviceLayer <<Service Layer>> #lightgreen

-> sdkClient ++ : incoming message

sdkClient -> consumer ++ : consumeMessage(messageContext)

consumer -> serviceLayer ++ : processMessage(messageText)

alt Service layer succeeds
    serviceLayer --> consumer --
    consumer -> consumer : context.complete()
else Service layer throws exception
    serviceLayer --> consumer -- : exception
    consumer -> consumer : context.abandon()
end

consumer --> sdkClient

[<-- sdkClient : acknowledge

@enduml
