@startuml
title Acknowledgements - File Handler Service Queue Subscriber
queue "Acknowledgements Queue" as acknowledgementsQueue <<Queue>> #lightgreen
participant "Opal File Handler Service" as fileHandlerService <<File Handler Service>> #LightSkyBlue
database "File Handler DB" as fileHandlerDb #lightgreen

acknowledgementsQueue -> fileHandlerService ++ : Item placed onto queue triggers subscriber
alt Process success DTO from queue
fileHandlerService -> fileHandlerDb ++ : Update Registrations table with vpfpo_registration_id, defendent_account_id and status
fileHandlerDb --> fileHandlerService -- : Confirmation of update
else Process error DTO
fileHandlerService -> fileHandlerDb ++ : Update status to be PUBLISHING_FAILED
fileHandlerDb --> fileHandlerService -- : Confirmation of update
end
fileHandlerService --> acknowledgementsQueue -- : Exit process
@enduml
