@startuml
title Acknowledgements - Fines Process
actor "User" as user
participant "Publish Draft Account" as publishDraftAccountsPage <<UI Page>> #lightskyblue
participant "Opal Fines Service" as finesService <<Fines Service>> #LightSkyBlue
queue "Create Draft Account Queue" as createDraftAccountQueue <<Queue>> #lightgreen
queue "Acknowledgements Queue" as acknowledgementsQueue <<Queue>> #lightgreen
database "Fines DB" as finesDb #lightgreen

publishDraftAccountsPage -> finesService ++ : Get draft accounts that have not been ingested today
finesService --> publishDraftAccountsPage -- : Return draft accounts (will be grouped by BU front end)
user -> publishDraftAccountsPage ++ : Select BU(s) to publish
publishDraftAccountsPage -> finesService ++ : PATCH /draft-accounts to publish accounts
finesService -> createDraftAccountQueue ++ : Push DTOs for publishing
createDraftAccountQueue --> finesService -- : Confirmation of pushing to queue
finesService -> acknowledgementsQueue ++ : Pushing acknowledgements DTO for file-handler to generate XML file
acknowledgementsQueue --> finesService -- : Confirmation of pushing to queue
finesService -> finesDb ++ : Updating status of draft account to be PUBLISHED
finesDb --> finesService -- : Confirmation of update
finesService --> publishDraftAccountsPage -- : Confirmation of publishing
publishDraftAccountsPage --> user -- : Display success message
@enduml
