@startuml
title Generate Acknowledgements XML File
participant "Kubernetes CronJob" as cronjob <<External System>> #LightCoral
participant "Opal File Handling Service" as fileHandlingService <<File Handling Service>> #LightSkyBlue
database "Opal File Handling Database" as fileHandlingDb #LightGreen
database "Opal File Handling Blob Storage" as fileHandlingBlobStorage #LightGreen
database "External Interface Blob Store" as externalInterfaceBlobStore <<External System>> #LightCoral

cronjob -> fileHandlingService ++ : Trigger Acknowledgements XML file generation
fileHandlingService -> fileHandlingDb ++ : Retrieve Acknowledgements grouped by file_gen, CTO and LJA code
fileHandlingDb --> fileHandlingService -- : Return Acknowledgements
fileHandlingService -> fileHandlingService : Generate XML File with each acknowledgement its own XML object
fileHandlingService -> fileHandlingBlobStorage ++ : Store Acknowledgements XML File in Opal Blob Store
fileHandlingBlobStorage --> fileHandlingService -- : Confirmation of storage
fileHandlingService -> externalInterfaceBlobStore ++ : Store Acknowledgements XML File in External Interface Blob Store
externalInterfaceBlobStore --> fileHandlingService -- : Confirmation of Storage
fileHandlingService --> cronjob -- : Exit process
@enduml