@startuml
title Get interface files
participant "Any opal service" as anyOpalService <<Any Opal Service>> #LightSkyBlue
participant "Opal File Handling Service" as fileHandlingService <<File Handling Service>> #LightSkyBlue
database "Opal File Handling Database" as fileHandlingDb #LightGreen

anyOpalService -> fileHandlingService ++ : Request to get interface files
fileHandlingService -> fileHandlingService : Checks if feature flag for this API is enabled
fileHandlingService -> fileHandlingDb ++ : Query database for file metadata using provided search criteria
fileHandlingDb --> fileHandlingService -- : Return all file metadata matching search criteria or empty result if no matches found
fileHandlingService -> anyOpalService : Return list of file metadata to requester
@enduml