@startuml
title Read file from BAIS and store in OPAL
participant "Kubernetes CronJob" as cronjob <<External System>> #LightCoral
participant "Opal File Handling Service" as fileHandlingService <<File Handling Service>> #LightSkyBlue
database "Opal File Handling Database" as fileHandlingDb #LightGreen
database "Opal File Handling Blob Storage" as fileHandlingBlobStorage #LightGreen
database "BAIS SFTP Server" as baisSftpServer <<External System>> #LightCoral

cronjob -[#red]> fileHandlingService ++ : Trigger file storage process
fileHandlingService -[#red]> fileHandlingService : Checks if feature flag for this Job is enabled
fileHandlingService -[#red]> baisSftpServer ++ : Connect to SFTP server and retrieve files
baisSftpServer -[#red]-> fileHandlingService -- : Return files
fileHandlingService -[#red]-> fileHandlingDb ++ : Check for existing file metadata to prevent duplicates (Must have status of successful to be a duplicate) (JPA)
fileHandlingDb -[#red]-> fileHandlingService -- : Return existing metadata if found or confirmation of no duplicates

fileHandlingService -[#red]> fileHandlingService : Start transaction
fileHandlingService -[#red]> fileHandlingBlobStorage ++ : Store files in blob storage
fileHandlingBlobStorage -[#red]-> fileHandlingService -- : Confirmation of storage
fileHandlingService -[#red]> fileHandlingDb ++ : Add row to database with file metadata (JPA) with a success status (or duplicate status if duplicate found)
fileHandlingDb -[#red]-> fileHandlingService -- : Confirmation of update
alt Duplicates found
    fileHandlingService -[#red]> fileHandlingService : Log error that duplicates were found
else
    fileHandlingService -> fileHandlingService: Process BAIS file if applicable
end
fileHandlingService -[#red]> fileHandlingService : Commit transaction
fileHandlingService -[#red]> baisSftpServer ++ : Delete BAIS files we have successfully stored in opal and have metadata updated in database
baisSftpServer -[#red]-> fileHandlingService -- : Confirmation of deletion
fileHandlingService -> cronjob -- : Exit process
@enduml