@startuml
title Transform the VPFPO file into source JSON and add to processing queue

participant "Opal File Handling Service" as fileHandlingService <<File Handling Service>> #LightSkyBlue
database "Opal File Handling Blob Storage" as fileHandlingBlobStorage #LightGreen
database "Opal File Handling Database" as fileHandlingDb #LightGreen
queue "Fines Draft Account queue" as finesDraftAccountQueue <<Queue>> #lightgreen


fileHandlingService -> fileHandlingService ++: Read source file to extract key data to populate the source JSON file
fileHandlingService -> fileHandlingDb ++ : Using the extract data from the source file locate the relevant reference data (BU / Area (incl. PSA-BU Mapping), opal processing domain, etc)
fileHandlingDb --> fileHandlingService -- : Return data
fileHandlingService -> fileHandlingService : Create the source JSON file using the extract data from the source file and reference data from the database
fileHandlingService -> fileHandlingBlobStorage ++ : Store source JSON in blob storage
fileHandlingBlobStorage --> fileHandlingService -- : Confirmation of storage with location metadata
fileHandlingService -> fileHandlingDb ++ : Store file metadata in database (JPA) with a success status
fileHandlingDb --> fileHandlingService -- : Confirmation of update

fileHandlingService -> finesDraftAccountQueue ++ : Send JSON Draft Account payload to queue
finesDraftAccountQueue --> fileHandlingService -- : Confirmation of message sent
fileHandlingService -> fileHandlingDb ++ : Mark status as successfully processed in database (JPA) or if error occurs mark as failed with error message in database (JPA)
fileHandlingDb --> fileHandlingService -- : Confirmation of update

@enduml