@startuml
actor "User" as user
participant "View account" as viewAccount <<UI Page>> #lightskyblue
participant "Comments" as comments <<UI Page>> #lightskyblue
participant "Add account note" as addNote <<UI Page>> #lightskyblue
participant "Get Defendant Account \nHeader Summary" as getHeaderApi <<Fines API>> #lightgreen
participant "Get Defendant Account \nAt A Glance" as getAAGApi <<Fines API>> #lightgreen
database "Fines DB" as db #lightgreen

user ->  viewAccount ++ :Navigates to
viewAccount --> getHeaderApi : Get header data
getHeaderApi --> db ++ : Get header data (JPA)
db --> getHeaderApi : Return header data
getHeaderApi --> viewAccount : Return header data (JSON)
viewAccount -> viewAccount : Display header
viewAccount --> getAAGApi : Get At a Glance data
getAAGApi --> db : Get At a Glance data (JPA)
db --> getAAGApi : Return At a Glance data
getAAGApi --> viewAccount : Return At a Glance data (JSON)
viewAccount -> viewAccount : Display At a Glance tab


@enduml