@startuml
actor "FAE User" as user
participant "View Account \n(Enforcement tab)" as page <<UI Page>> #lightskyblue
participant "Get Defendant Account\nEnforcement Status" as enfapi <<Fines API>> #lightgreen
database "Get Defendant Account\nEnforcement Status" as enfdb <<Fines DB>>  #lightgreen
user -> page ++: Select Enforcement tab
page ->> enfapi ++
enfapi -> enfdb ++ : Defendant Account ID (JPA with DB view)
enfapi <-- enfdb --: Defendant Account Enforcement Status
page <-- enfapi -- : Defendant Account Enforcement Status (JSON)
page -> page : Display Enforcement tab
@enduml