actor "FAE User" as user
participant "Defendant Account\n(Enforcement tab)" as page <<UI Page>> #lightskyblue
participant "Add Enforcement Action" as enfpage <<UI Page>> #lightskyblue
participant "Enforcement Action Responses" as respage <<UI Page>> #lightskyblue
participant "Get Defendant Account\nNext Enforcement Actions" as nextenfapi <<Fines API>> #lightgreen
database "Get Defendant Account\nNext Enforcement Actions" as nextenfsp <<Fines SP>>  #lightgreen
user -> page : Select <b>Add enforcement action</b> link
autoactivate on
page -> enfpage : route to
enfpage -> nextenfapi : Defendant Account ID
nextenfapi -> nextenfsp : Defendant Account ID
nextenfapi <-- nextenfsp : Next Enforcement Actions
enfpage <-- nextenfapi : Next Enforcement Actions (JSON)
enfpage -> enfpage : Display list of Next Enforcement Actions
user -> enfpage : Select <b>Next Enforcement Action</b> from the list
enfpage -> respage : route to
user -> respage : Enter Responses