@startuml
actor "User" as user
participant "Select Business Unit" as selectBU <<UI Page>> #lightskyblue
participant "Process and Allocate" as proAll <<UI Page>> #lightskyblue
participant "Get Interface Jobs Processed File Summary" as interfaceFiles <<Fines API>> #lightgreen
database "Fines DB" as db <<DB View>> #lightgreen


user -> selectBU --++: Selects Business Units \nand clicks 'Continue'
selectBU -> proAll --++: Navigate to
proAll -> interfaceFiles ++: List of Business Unit IDs \n and Statuses
interfaceFiles -> db ++ : Get Interface Files \nfor Business Units and Statuses
interfaceFiles <-- db --: Interface Files Summaries
proAll <-- interfaceFiles --: Interface Files Summaries
alt Process Tab
proAll -> proAll : Display 'Created' or 'Failed' Interface Files \n and 'Ignored' file count
else Allocate Tab
proAll -> proAll : Display 'Complete' Interface Files and 'Processing' file count \n and 'Ignored' file count
else Ignore Tab
proAll -> proAll : Display 'Ignored' Interface Files
end

@enduml