@startuml
actor "Inputter" as user
participant "Account Details" as ad <<UI Page>> #lightskyblue
participant "Withdraw Transfer" as wt <<UI Page>> #lightskyblue
participant "Remove Latest \nDefendant Account Transfer" as rldat <<Fines API>> #lightgreen
database "Fines SP" as db <<Withdraw Transfer Out>> #lightgreen

user -> ad ++ : Clicks 'More actions' dropdown
user -> ad : Chooses 'Withdraw Transfer' option
ad -> wt ++ : Navigate to
user -> wt : Clicks 'Withdraw Transfer' button
wt --> rldat ++ : Defendant Account details (JSON)
rldat -> db ++ : Withdraw Transfer Out (SP)
rldat <-- db -- : Withdraw Transfer Out Result
wt <-- rldat -- : Withdraw Transfer Out Result (JSON)


@enduml