@startuml
actor "User" as user
participant "View account" as viewAccount <<UI Page>> #lightskyblue
participant "Get Major Creditor Account \nHeader Summary" as getHeaderApi <<Fines API>> #lightgreen
participant "Get Major Creditor Account \nAt A Glance" as getAAGApi <<Fines API>> #lightgreen
database "Fines DB" as db <<DB View>> #lightgreen
participant "GMAS DAC" as gmasdac <<API>> #yellow
database "Get Defendant Account Header Summary" as dblegacyHS <<GOB SP>> #yellow
database "Get Defendant Account At A Glance" as dblegacyAAG <<GOB SP>> #yellow

user ->  viewAccount ++ :Navigates to
viewAccount --> getHeaderApi ++: Get header data
alt Opal Mode
getHeaderApi --> db ++ : Get header data (JPA)
db --> getHeaderApi : Return header data
deactivate db
else Legacy Mode
getHeaderApi --> gmasdac ++ : Get header data (JSON)
gmasdac -> gmasdac : Convert JSON to XML
gmasdac --> dblegacyHS ++ : Get header data (XML)
dblegacyHS --> gmasdac -- : Return header data (XML)
gmasdac --> getHeaderApi -- : Return header data (XML)
getHeaderApi -> getHeaderApi : Convert XML to JSON
end
getHeaderApi --> viewAccount : Return header data (JSON)
deactivate getHeaderApi
viewAccount -> viewAccount : Display header
viewAccount --> getAAGApi ++: Get At a Glance data
alt Opal Mode
getAAGApi --> db ++ : Get At a Glance data (JPA)
db --> getAAGApi : Return At a Glance data
deactivate db
else Legacy Mode
getAAGApi --> gmasdac ++ : Get At a Glance data (JSON)
gmasdac -> gmasdac : Convert JSON to XML
gmasdac --> dblegacyAAG ++ : Get At a Glance data (XML)
dblegacyAAG --> gmasdac -- : Return At a Glance data (XML)
gmasdac --> getAAGApi -- : Return At a Glance data (XML)
getAAGApi -> getAAGApi : Convert XML to JSON
end
getAAGApi --> viewAccount : Return At a Glance data (JSON)
deactivate getAAGApi
viewAccount -> viewAccount : Display At a Glance tab



@enduml