@startuml
actor "User" as user
participant "View account" as viewAccount <<UI Page>> #lightskyblue
participant "Add note" as notes <<UI Page>> #lightskyblue
participant "Add Note" as postNote <<Fines API>> #lightgreen
database "Fines DB" as db #lightgreen
participant "GMAS DAC" as gmasdac <<API>> #yellow
database "Create note" as dblegacy <<GOB SP>> #yellow


user ->  viewAccount ++ : Click Header \n'Add account note' button
viewAccount -> notes ++ :Navigates to
deactivate viewAccount
user ->  notes : Inputs data
user ->  notes : Clicks 'Save Note' button
notes --> postNote ++: Create note
alt Opal Mode
postNote --> db ++: Create note (JPA)
db --> postNote: Return created data
deactivate db
else Legacy Mode
postNote --> gmasdac ++: Create note (JSON)
gmasdac -> gmasdac : Convert JSON to XML
gmasdac --> dblegacy ++: Create note (XML)
dblegacy --> gmasdac --: Return created data (XML)
gmasdac --> postNote --: Return created data (XML)
postNote -> postNote : Convert XML to JSON
end
postNote --> notes : Return created data (JSON)
deactivate postNote
notes -> viewAccount ++: Navigates to
deactivate notes

@enduml