@startuml
actor User
participant "View Account \n(Creditor Tab)" as viewScreen <<UI Page>> #lightskyblue
participant "Get Minor Creditor Account Party" as getapi <<Fines API>> #lightgreen
database "Fines Database" as db #lightgreen
participant "Get Minor Creditor Account Party" as gmasdac <<GMAS DAC>> #yellow
database "Get Minor Creditor Account Party" as dblegacy <<GOB SP>> #yellow

User -> viewScreen ++ : Navigates to tab
viewScreen --> getapi ++ : Minor Creditor Account ID & Party ID
alt Opal Mode
getapi --> db ++ : Get data (JPA)
db --> getapi -- : Return data (JSON)
else Legacy Mode
getapi --> gmasdac ++ : Get data (JSON)
gmasdac -> gmasdac: Convert JSON to XML
gmasdac --> dblegacy ++ : Get data (SP)
dblegacy --> gmasdac -- : Return data
gmasdac --> getapi -- : Return data (XML)
getapi -> getapi : Convert XML to JSON
end
getapi --> viewScreen --: Return data (JSON)
viewScreen -> viewScreen : Display data
getapi --
@enduml