@startuml
actor User
participant "View Account \n(Creditor Tab)" as viewScreen <<UI Page>> #lightskyblue
participant "Amend Minor Creditor\nDetails" as changeScreen <<UI Page>> #lightskyblue
participant "Replace Minor Creditor\nAccount Party" as putapi <<Fines API>> #lightgreen
database "Fines Database" as db #lightgreen
participant "Replace Minor Creditor\nAccount Party" as gmasdac <<GMAS DAC>> #yellow
database "Replace Minor Creditor\nAccount Party" as dblegacy <<GOB SP>> #yellow

User -> viewScreen ++ : Clicks 'Change' link
viewScreen --> changeScreen ++--: Navigate to Change screen
User -> changeScreen : Makes changes and submits
changeScreen --> putapi ++ : Minor Creditor & Party data (JSON)
alt Opal Mode
putapi --> db ++ : Replace data (JPA)
db --> putapi -- : Return data (JSON)
else Legacy Mode
putapi --> gmasdac ++ : Replace data (JSON)
gmasdac -> gmasdac: Convert JSON to XML
gmasdac --> dblegacy ++ : Replace data (SP)
dblegacy --> gmasdac -- : Return data
gmasdac --> putapi -- : Return data (XML)
putapi -> putapi : Convert XML to JSON
end
putapi --> changeScreen --: Return data (JSON)
changeScreen -> viewScreen --++: Navigate to & Display data
putapi --
@enduml
