@startuml
actor "User" as user
participant "View account" as viewAccount <<UI Page>> #lightskyblue
participant "Get Defendant Account \nHeader Summary" as getHeaderApi <<Fines API>> #lightgreen
participant "Get Defendant Account \nAt A Glance" as getAAGApi <<Fines API>> #lightgreen
database "GMAS DAC" as legacyApi <<Legacy API>> #yellow
database "GOB" as db <<Legacy SP>>#yellow

user ->  viewAccount ++ : Navigates to

group Initial fetch
  viewAccount --> getHeaderApi ++: Get header data
  getHeaderApi --> legacyApi ++ : Get header data
    legacyApi --> db ++ : Get header data
    db --> legacyApi -- : Return header data & account version
    legacyApi --> getHeaderApi -- : Return header data\n& account version
  getHeaderApi --> viewAccount -- : Return header data\n& account version (ETag)
  viewAccount -> viewAccount : Display header\n & store account version as <b>base version</b>.


  viewAccount --> getAAGApi ++: Get At a Glance data
  getAAGApi --> legacyApi ++ : Get At a Glance data
  legacyApi --> db ++ : Get AAG data
  db --> legacyApi -- : Return AAG data \n& account version
  legacyApi --> getAAGApi -- : Return AAG data \n& account version
  getAAGApi --> viewAccount -- : Return AAG data\n& account version (ETag)
end
viewAccount -> viewAccount : Display "At a Glance" tab
opt base version != account version
  viewAccount -> viewAccount : Show "Refresh" banner
  note over viewAccount
    Banner shows a Refresh button.
  end note
    user -> viewAccount : Click Refresh
    group Refresh fetch (re-run APIs)
  viewAccount --> getHeaderApi ++: Get header data
  getHeaderApi --> legacyApi ++ : Get header data
    legacyApi --> db ++ : Get header data
    db --> legacyApi -- : Return header data & account version
    legacyApi --> getHeaderApi -- : Return header data\n& account version
  getHeaderApi --> viewAccount -- : Return header data\n& account version (ETag)
  viewAccount -> viewAccount : Display header\n & store account version as <b>base version</b>.


  viewAccount --> getAAGApi ++: Get At a Glance data
  getAAGApi --> legacyApi ++ : Get At a Glance data
  legacyApi --> db ++ : Get AAG data
  db --> legacyApi -- : Return AAG data \n& account version
  legacyApi --> getAAGApi -- : Return AAG data \n& account version
  getAAGApi --> viewAccount -- : Return AAG data\n& account version (ETag)
end
    viewAccount -> viewAccount : Show "Confirm" banner
      note over viewAccount
        Banner shows confirmation and Dismiss button.
      end note
    viewAccount -> viewAccount : Display "At a Glance" tab
end

@enduml
